export const cricketMatches = [
  {
    matchId: 101,
    match: 15,
    date: "September 13, 2024",
    location: "Bridgetown",
    status: "finished",
    startTime: "7:00 PM",
    teams: {
      BarbadosRoyals: {
        score: 156,
        wickets: 7,
        overs: 20,
      },
      TrinbagoKnightRiders: {
        score: 159,
        wickets: 8,
        overs: 19.5,
      },
    },
    winner: "Trinbago Knight Riders",
    result: "Trinbago won by 2 wickets (with 1 ball remaining)",
    topScorer: "Chris Gayle",
    bestBowler: "Sunil Narine",
  },
  {
    matchId: 102,
    match: 3,
    date: "September 12-15, 2024",
    location: "Anantapur",
    status: "live",
    startTime: "10:00 AM",
    teams: {
      IndiaA: {
        firstInnings: 290,
        secondInnings: 154,
        totalRuns: 444,
        wickets: 2,
        overs: 125,
      },
      IndiaD: {
        firstInnings: 183,
        secondInnings: null,
        totalRuns: null,
        wickets: null,
      },
    },
    lead: "India A lead by 261 runs",
    topScorer: "Prithvi Shaw",
    bestBowler: "Mohammed Siraj",
  },
  {
    matchId: 102,
    match: 3,
    date: "September 12-15, 2024",
    location: "Anantapur",
    status: "live",
    startTime: "10:00 AM",
    teams: {
      IndiaA: {
        firstInnings: 290,
        secondInnings: 154,
        totalRuns: 444,
        wickets: 2,
        overs: 125,
      },
      IndiaD: {
        firstInnings: 183,
        secondInnings: null,
        totalRuns: null,
        wickets: null,
      },
    },
    lead: "India A lead by 261 runs",
    topScorer: "Prithvi Shaw",
    bestBowler: "Mohammed Siraj",
  },

  {
    matchId: 103,
    match: "1st Semi Final",
    date: "September 14, 2024",
    location: "Birmingham",
    status: "upcoming",
    startTime: "3:30 PM",
    teams: {
      Surrey: {
        predictedScore: "180/6",
        keyPlayer: "Kane Williamson",
      },
      Somerset: {
        predictedScore: "175/5",
        keyPlayer: "Tom Banton",
      },
    },
    expectedWeather: "Partly cloudy with a chance of rain",
    venueCapacity: 25000,
  },
  {
    matchId: 103,
    match: "1st Semi Final",
    date: "September 14, 2024",
    location: "Birmingham",
    status: "upcoming",
    startTime: "3:30 PM",
    teams: {
      Surrey: {
        predictedScore: "180/6",
        keyPlayer: "Kane Williamson",
      },
      Somerset: {
        predictedScore: "175/5",
        keyPlayer: "Tom Banton",
      },
    },
    expectedWeather: "Partly cloudy with a chance of rain",
    venueCapacity: 25000,
  },
  {
    matchId: 103,
    match: "1st Semi Final",
    date: "September 14, 2024",
    location: "Birmingham",
    status: "upcoming",
    startTime: "3:30 PM",
    teams: {
      Surrey: {
        predictedScore: "180/6",
        keyPlayer: "Kane Williamson",
      },
      Somerset: {
        predictedScore: "175/5",
        keyPlayer: "Tom Banton",
      },
    },
    expectedWeather: "Partly cloudy with a chance of rain",
    venueCapacity: 25000,
  },
  {
    matchId: 103,
    match: "1st Semi Final",
    date: "September 14, 2024",
    location: "Birmingham",
    status: "upcoming",
    startTime: "3:30 PM",
    teams: {
      Surrey: {
        predictedScore: "180/6",
        keyPlayer: "Kane Williamson",
      },
      Somerset: {
        predictedScore: "175/5",
        keyPlayer: "Tom Banton",
      },
    },
    expectedWeather: "Partly cloudy with a chance of rain",
    venueCapacity: 25000,
  },
  {
    matchId: 102,
    match: 3,
    date: "September 12-15, 2024",
    location: "Anantapur",
    status: "live",
    startTime: "10:00 AM",
    teams: {
      IndiaA: {
        firstInnings: 290,
        secondInnings: 154,
        totalRuns: 444,
        wickets: 2,
        overs: 125,
      },
      IndiaD: {
        firstInnings: 183,
        secondInnings: null,
        totalRuns: null,
        wickets: null,
      },
    },
    lead: "India A lead by 261 runs",
    topScorer: "Prithvi Shaw",
    bestBowler: "Mohammed Siraj",
  },
];
